# -*- coding: utf-8 -*-
"""KNN with PSO Optimization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I94tcZc1RXmh5D1f2r8QjG6et_8TBySZ
"""

pip install nltk

pip install niapy

"""Import library yang dibutuhkan"""

from sklearn.model_selection import train_test_split, cross_val_score

from niapy.problems import Problem
from niapy.task import Task
from niapy.algorithms.basic import ParticleSwarmOptimization

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.datasets import make_blobs
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

"""Import data"""

data = pd.read_excel('data.xlsx')
data

"""Data checking"""

#getting an over-view about all columns present in the dataset
data.info()

#Total number of data records that have a null value in them
data.isnull().sum()

count=0
for i in data['content']:
    if count==5:
        break
    print(i)
    print()
    count+=1

"""Pre-processing data"""

data = data.drop(columns=['userName', 'at'], axis=1)
data

!pip3 install contractions

import contractions
from tqdm import tqdm
#tqdm package is used to track the progress of work. It displays the percentage of loop done.

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
#donwloadin the stopwords of indonesia language
stopwords=stopwords.words('indonesian')
#Removing stopwords "tidak"
print('tidak' in stopwords)
stopwords.remove('tidak')
print('tidak' in stopwords)

import regex as re
processed_reviews=[]
for i in tqdm(data['content']):
    #Regular expression that removes all the html tags pressent in the reviews
    i=re.sub('(<[\w\s]*/?>)',"",i)
    #Expanding all the contractions present in the review to is respective actual form
    i=contractions.fix(i)
    #Removing all the special charactesrs from the review text
    i=re.sub('[^a-zA-Z0-9\s]+',"",i)
    #Removing all the digits present in the review text
    i=re.sub('\d+',"",i)
    #Making all the review text to be of lower case as well as remvoing the stopwords and words of length less than 3
    processed_reviews.append(" ".join([j.lower() for j in i.split() if j not in stopwords and len(j)>=3]))

# Membuat dataframe dari data
dataframe = pd.DataFrame(processed_reviews)

# Menyimpan dataframe ke file Excel
dataframe.to_excel('data cleaned.xlsx', index=False)

##Pelabelan
kalimat = pd.read_excel("data cleaned.xlsx")

#skoring
# Membuka file txt
positive_words = open('positive-words.txt', 'r')
positif = positive_words.readlines()
# Menghilangkan karakter newline
positif = [word.strip() for word in positif]

negative_words = open('negative-words.txt', 'r')
negatif = negative_words.readlines()
negatif = [word.strip() for word in negatif]

import re
from string import punctuation
from collections import defaultdict

scores = []
for i in range(0,(len(kalimat[0]))):
  kalimat2 = str(kalimat[0][i])
  kata2 = kalimat2.split()
  positif_matches = [kata for kata in kata2 if kata in positif]
  negatif_matches = [kata for kata in kata2 if kata in negatif]
  score = len(positif_matches) - len(negatif_matches)
  scores.append(score)
  scores_df = {'score': scores, 'text': kalimat[0]}

#Creating a new datafram using the Processed Reviews
processed_df=pd.DataFrame(scores_df)

processed_df.head()

# CONVERT SCORE TO SENTIMENT
processed_df['score'] = np.where(processed_df['score'] < 0, 0, 1)

processed_df = processed_df.dropna()

#Splitting the data into dependent and independent variables i.e, features and the target columns
X=processed_df['text']
Y=processed_df['score']

"""Splitting data"""

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, stratify=Y, random_state=1234)

def print_shape(a,b):
    """
    Function that prints the shape of the numpy arrays passed as arguments
    """
    print("Size of Training Samples")
    print("="*30)
    print(a.shape)
    print("Size of Testing Samples")
    print("="*30)
    print(b.shape)
print_shape(X_train,X_test)

"""Vektorisasi data review"""

from sklearn.feature_extraction.text import CountVectorizer
#Using CountVectorizer to convert text into tokens/features
vect = CountVectorizer()
#Using training data to transform text into counts of features for each message
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_test_dtm = vect.transform(X_test)

"""KNN"""

pip install pyswarm

from pyswarm import pso
knn = KNeighborsClassifier()
knn.fit(X_train_dtm,y_train)
print('Accuracy:', knn.score(X_test_dtm, y_test))

"""KNN with PSO Optimization"""

# Optimalisasi dengan PSO
import random
random.seed(123)
def optimize_knn(k):
  knn.neighbors = int(k[0])
  return knn.score(X_train_dtm,y_train)

lb = [1]
ub = [15]

xopt,fopt = pso(optimize_knn,lb,ub)
xopt # Ini adalah nilai K paling optimal

fopt # Ini adalah nilai score paling optimal

xopt[0]

knn_pso = KNeighborsClassifier(n_neighbors=round(xopt[0]))

knn_pso.fit(X_train_dtm, y_train)
print('Accuracy:', knn_pso.score(X_test_dtm, y_test))

"""Model Comparison"""

from sklearn.metrics import roc_curve, auc
train_fpr_knn,train_tpr_knn,thresholds_knn=roc_curve(y_train,knn.predict_proba(X_train_dtm)[:,1])
test_fpr_knn,test_tpr_knn,thresholds_knn=roc_curve(y_test,knn.predict_proba(X_test_dtm)[:,1])

train_fpr_knn_pso,train_tpr_knn_pso,thresholds_knn_pso=roc_curve(y_train,knn_pso.predict_proba(X_train_dtm)[:,1])
test_fpr_knn_pso,test_tpr_knn_pso,thresholds_knn_pso=roc_curve(y_test,knn_pso.predict_proba(X_test_dtm)[:,1])

import matplotlib.pyplot as plt
# Make figure and axes
fig, axs = plt.subplots(2,2)

# Plotting in every axes
axs[0,0].plot(train_fpr_knn,train_tpr_knn,label="Training Accuracy="+str(round(auc(train_fpr_knn, train_tpr_knn),2)))
axs[0,0].plot(test_fpr_knn,test_tpr_knn,label="Testing Accuracy ="+str(round(auc(test_fpr_knn, test_tpr_knn),2)))
axs[0,0].legend()
axs[0,0].xlabel("Thresholds")
axs[0,0].ylabel("ACCURACY")
axs[0,0].title("KNN Training and Testing ROC Curves")

axs[1,0].plot(train_fpr_knn_pso,train_tpr_knn_pso,label="Training Accuracy="+str(round(auc(train_fpr_knn_pso, train_tpr_knn_pso),2)))
axs[1,0].plot(test_fpr_knn_pso,test_tpr_knn_pso,label="Testing Accuracy ="+str(round(auc(test_fpr_knn_pso, test_tpr_knn_pso),2)))
axs[1,0].legend()
axs[1,0].xlabel("Thresholds")
axs[1,0].ylabel("ACCURACY")
axs[1,0].title("KNN with PSO Training and Testing ROC Curves")

# Hide xlabels and tick labels
for ax in axs.flat:
  ax.label_outer()

plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
sns.heatmap(confusion_matrix(y_train,knn.predict(X_test_dtm)),annot=True)

sns.heatmap(confusion_matrix(y_test,knn_pso.predict(X_test_dtm)),annot=True)